In [1]:
import pandas as pd 
import numpy as np

# To load the CSV data into dataframe
df = pd.read_csv('faculty.csv')
# PART 1 Q1:
degree_formatted = [x.strip().replace('.', '').split() for x in df[' degree']]

set(reduce(lambda x,y: x+y,degree_formatted))

# PART 1 Q2: 
title_formatted = [x.strip().replace(' of Biostatistics', '').replace(' is Biostatistics', '') for x in df[' title']]
set(title_formatted)

# PART 1 Q3: 
email = df[' email']
print list(email)

# PART 1 Q4: 
email_domain = [x[x.find('@'):] for x in df[' email']]

set(email_domain)



['bellamys@mail.med.upenn.edu', 'warren@upenn.edu', 'bryanma@upenn.edu', 'jinboche@upenn.edu', 'sellenbe@upenn.edu', 'jellenbe@mail.med.upenn.edu', 'ruifeng@upenn.edu', 'bcfrench@mail.med.upenn.edu', 'pgimotty@upenn.edu', 'wguo@mail.med.upenn.edu', 'hsu9@mail.med.upenn.edu', 'rhubb@mail.med.upenn.edu', 'whwang@mail.med.upenn.edu', 'mjoffe@mail.med.upenn.edu', 'jrlandis@mail.med.upenn.edu', 'liy3@email.chop.edu', 'mingyao@mail.med.upenn.edu', 'hongzhe@upenn.edu', 'rlocalio@upenn.edu', 'nanditam@mail.med.upenn.edu', 'knashawn@mail.med.upenn.edu', 'propert@mail.med.upenn.edu', 'mputt@mail.med.upenn.edu', 'sratclif@upenn.edu', 'michross@upenn.edu', 'jaroy@mail.med.upenn.edu', 'msammel@cceb.med.upenn.edu', 'shawp@upenn.edu', 'rshi@mail.med.upenn.edu', 'hshou@mail.med.upenn.edu', 'jshults@mail.med.upenn.edu', 'alisaste@mail.med.upenn.edu', 'atroxel@mail.med.upenn.edu', 'rxiao@mail.med.upenn.edu', 'sxie@mail.med.upenn.edu', 'dxie@upenn.edu', 'weiyang@mail.med.upenn.edu']


{'@cceb.med.upenn.edu', '@email.chop.edu', '@mail.med.upenn.edu', '@upenn.edu'}

In [2]:
df

name               degree  \
0         Scarlett L. Bellamy                Sc.D.   
1            Warren B. Bilker                Ph.D.   
2             Matthew W Bryan                  PhD   
3                  Jinbo Chen                Ph.D.   
4           Susan S Ellenberg                Ph.D.   
5          Jonas H. Ellenberg                Ph.D.   
6                    Rui Feng                 Ph.D   
7          Benjamin C. French                  PhD   
8          Phyllis A. Gimotty                 Ph.D   
9                Wensheng Guo                 Ph.D   
10                Yenchih Hsu                Ph.D.   
11          Rebecca A Hubbard                  PhD   
12             Wei-Ting Hwang                Ph.D.   
13          Marshall M. Joffe          MD MPH Ph.D   
14          J. Richard Landis   B.S.Ed. M.S. Ph.D.   
15                   Yimei Li                Ph.D.   
16                 Mingyao Li                Ph.D.   
17                 Hongzhe Li                 Ph.D   
18         A. Russell Localio     JD MA MPH MS PhD   
19              Nandita Mitra                Ph.D.   
20        Knashawn H. Morales                Sc.D.   
21       Kathleen Joy Propert                Sc.D.   
22               Mary E. Putt              PhD ScD   
23       Sarah Jane Ratcliffe                Ph.D.   
24        Michelle Elana Ross                  PhD   
25               Jason A. Roy                Ph.D.   
26             Mary D. Sammel                Sc.D.   
27            Pamela Ann Shaw                  PhD   
28  Russell Takeshi Shinohara                    0   
29              Haochang Shou                Ph.D.   
30             Justine Shults                Ph.D.   
31        Alisa Jane Stephens                Ph.D.   
32         Andrea Beth Troxel                  ScD   
33                   Rui Xiao                  PhD   
34        Sharon Xiangwen Xie                Ph.D.   
35                  Dawei Xie                  PhD   
36           Wei (Peter) Yang                Ph.D.   

                                   title                        email  
0   Associate Professor of Biostatistics  bellamys@mail.med.upenn.edu  
1             Professor of Biostatistics             warren@upenn.edu  
2   Assistant Professor of Biostatistics            bryanma@upenn.edu  
3   Associate Professor of Biostatistics           jinboche@upenn.edu  
4             Professor of Biostatistics           sellenbe@upenn.edu  
5             Professor of Biostatistics  jellenbe@mail.med.upenn.edu  
6   Assistant Professor of Biostatistics            ruifeng@upenn.edu  
7   Associate Professor of Biostatistics  bcfrench@mail.med.upenn.edu  
8             Professor of Biostatistics           pgimotty@upenn.edu  
9             Professor of Biostatistics      wguo@mail.med.upenn.edu  
10  Assistant Professor of Biostatistics      hsu9@mail.med.upenn.edu  
11  Associate Professor of Biostatistics     rhubb@mail.med.upenn.edu  
12  Associate Professor of Biostatistics    whwang@mail.med.upenn.edu  
13            Professor of Biostatistics    mjoffe@mail.med.upenn.edu  
14            Professor of Biostatistics  jrlandis@mail.med.upenn.edu  
15  Assistant Professor of Biostatistics          liy3@email.chop.edu  
16  Associate Professor of Biostatistics   mingyao@mail.med.upenn.edu  
17            Professor of Biostatistics            hongzhe@upenn.edu  
18  Associate Professor of Biostatistics           rlocalio@upenn.edu  
19  Associate Professor of Biostatistics  nanditam@mail.med.upenn.edu  
20  Associate Professor of Biostatistics  knashawn@mail.med.upenn.edu  
21            Professor of Biostatistics   propert@mail.med.upenn.edu  
22            Professor of Biostatistics     mputt@mail.med.upenn.edu  
23  Associate Professor of Biostatistics           sratclif@upenn.edu  
24  Assistant Professor is Biostatistics           michross@upenn.edu  
25  Associate Professor of Biostatistics     jaroy@mail.med.upenn.edu  
26            Professor of B

In [205]:
import pandas as pd 
import numpy as np

# To load the CSV data into dataframe
df = pd.read_csv('faculty.csv')


formatted_name = df['name'].str.split().str[-1]
formatted_name.tolist() 

title_formatted = [x.strip().replace(' of Biostatistics', '').replace(' is Biostatistics', '') for x in df[' title']]
df['title_formatted']=title_formatted

df['surname']=formatted_name.tolist() 

df['first name']=formatted_name.tolist() 
df1=df[['surname',' degree', 'title_formatted', ' email']]

s=df1.values.tolist()
keys= df1['surname'].tolist()

formatted_firstname = df['name'].str.split().str[1]

# create a dictionary with empty list
faculty_dict = dict.fromkeys(keys, [])

# PART III Q6: 
for k in faculty_dict.keys():
    for i in range(len(s)):
        if k == s[i][0]:
            faculty_dict[k] = faculty_dict[k] + [(s[i][1:])]

for k in faculty_dict.keys()[:3]:
    print k
    print faculty_dict[k]
    
    

Putt
[[' PhD ScD', 'Professor', 'mputt@mail.med.upenn.edu']]
Feng
[[' Ph.D', 'Assistant Professor', 'ruifeng@upenn.edu']]
Bilker
[['Ph.D.', 'Professor', 'warren@upenn.edu']]


In [263]:
# PART III Q7: 
formatted_firstname = df['name'].str.split().str[0].tolist()

df['first name']=formatted_firstname 

keys= df['first name'].tolist()
df2=df[['first name','surname',' degree', 'title_formatted', ' email']]
s2=df2.values.tolist()


# create a dictionary with empty list
keys2= zip(df2['first name'].tolist(), df2['surname'].tolist())
professor_dict = dict.fromkeys(keys2, [])

for (i,j) in professor_dict.keys():
    for k in range(len(s2)):
        if i == s2[k][0] and j == s2[k][1]:
            professor_dict[(i,j)] = (s[k][1:])

for k in sorted(professor_dict.keys())[:3]:
    print k
    print professor_dict[k]

('A.', 'Localio')
[' JD MA MPH MS PhD', 'Associate Professor', 'rlocalio@upenn.edu']
('Alisa', 'Stephens')
[' Ph.D.', 'Assistant Professor', 'alisaste@mail.med.upenn.edu']
('Andrea', 'Troxel')
[' ScD', 'Professor', 'atroxel@mail.med.upenn.edu']


In [270]:
sorted(x.items(), key=lambda x: professor_dict.keys()[])

AttributeError: 'str' object has no attribute 'items'

In [280]:
sorted(professor_dict.keys(), key=lambda x: x[1])


[('Scarlett', 'Bellamy'),
 ('Warren', 'Bilker'),
 ('Matthew', 'Bryan'),
 ('Jinbo', 'Chen'),
 ('Jonas', 'Ellenberg'),
 ('Susan', 'Ellenberg'),
 ('Rui', 'Feng'),
 ('Benjamin', 'French'),
 ('Phyllis', 'Gimotty'),
 ('Wensheng', 'Guo'),
 ('Yenchih', 'Hsu'),
 ('Rebecca', 'Hubbard'),
 ('Wei-Ting', 'Hwang'),
 ('Marshall', 'Joffe'),
 ('J.', 'Landis'),
 ('Yimei', 'Li'),
 ('Hongzhe', 'Li'),
 ('Mingyao', 'Li'),
 ('A.', 'Localio'),
 ('Nandita', 'Mitra'),
 ('Knashawn', 'Morales'),
 ('Kathleen', 'Propert'),
 ('Mary', 'Putt'),
 ('Sarah', 'Ratcliffe'),
 ('Michelle', 'Ross'),
 ('Jason', 'Roy'),
 ('Mary', 'Sammel'),
 ('Pamela', 'Shaw'),
 ('Russell', 'Shinohara'),
 ('Haochang', 'Shou'),
 ('Justine', 'Shults'),
 ('Alisa', 'Stephens'),
 ('Andrea', 'Troxel'),
 ('Rui', 'Xiao'),
 ('Sharon', 'Xie'),
 ('Dawei', 'Xie'),
 ('Wei', 'Yang')]

In [282]:
# PART III Q8: 

print sorted(professor_dict.keys(), key=lambda x:x[1])



[('Scarlett', 'Bellamy'), ('Warren', 'Bilker'), ('Matthew', 'Bryan'), ('Jinbo', 'Chen'), ('Jonas', 'Ellenberg'), ('Susan', 'Ellenberg'), ('Rui', 'Feng'), ('Benjamin', 'French'), ('Phyllis', 'Gimotty'), ('Wensheng', 'Guo'), ('Yenchih', 'Hsu'), ('Rebecca', 'Hubbard'), ('Wei-Ting', 'Hwang'), ('Marshall', 'Joffe'), ('J.', 'Landis'), ('Yimei', 'Li'), ('Hongzhe', 'Li'), ('Mingyao', 'Li'), ('A.', 'Localio'), ('Nandita', 'Mitra'), ('Knashawn', 'Morales'), ('Kathleen', 'Propert'), ('Mary', 'Putt'), ('Sarah', 'Ratcliffe'), ('Michelle', 'Ross'), ('Jason', 'Roy'), ('Mary', 'Sammel'), ('Pamela', 'Shaw'), ('Russell', 'Shinohara'), ('Haochang', 'Shou'), ('Justine', 'Shults'), ('Alisa', 'Stephens'), ('Andrea', 'Troxel'), ('Rui', 'Xiao'), ('Sharon', 'Xie'), ('Dawei', 'Xie'), ('Wei', 'Yang')]


In [387]:
A = [[1,2,3],[2,7,4]]
B = [[1,-1],[0,1]]
C = [[5,-1],[9,1],[6,0]]
D = [[3,-2,-1],[1,2,3]]
u = [[6,2,-3,5]]
v = [[3,5,-1,4]]
w = [[1],[8],[0],[5]]

## 1.1 dimension of A
print "A:",len(A),"x",len(A[0])

## 1.2 dimension of B
print "B:",len(B),"x",len(B[0])

## 1.3 dimension of C
print "C:",len(C),"x",len(C[0])

## 1.4 dimension of D
print "D:",len(D),"x",len(D[0])

## 1.5 dimension of u
print "u:",len(u),"x",len(u[0])

## 1.6 dimension of w
print "w:",len(w),"x",len(w[0])

## 2.1
print map(lambda i: map(lambda x,y:x+y, u[i],v[i]), range(len(u)))

## 2.2
print map(lambda i: map(lambda x,y:x-y, u[i],v[i]), range(len(u)))

## 2.3
alpha = 6
print map(lambda i: map(lambda x:alpha*x, u[i]), range(len(u)))

## 2.4
print map(lambda i: map(lambda x,y:x*y, u[i],v[i]), range(len(u)))

## 2.5
from math import sqrt()
j=0
for i in range(len(u[0])):
    j += u[0][i]**2
print sqrt(j)

## 3.1 - not defined

## 3.2 
C_T = zip(*C)
print map(lambda i: map(lambda x,y:x-y, A[i],C_T[i]), range(len(A)))

## 3.3
print map(lambda i: map(lambda x,y:x+3*y, C_T[i],D[i]), range(len(A)))

## 3.4
import numpy as np

mB = np.matrix(B)
mA = np.matrix(A)

print mB*mA

## 3.5 - not defined

## 3.6 - not defined

## 3.7 
mC = np.matrix(C)
print mC*mB

## 3.8
print mB**4

## 3.9
A_T = zip(*A)
mA_T = np.matrix(A_T)
print mA*mA_T

## 3.10
D_T = zip(*D)

mD = np.matrix(D)
mD_T = np.matrix(D_T)
print mD_T*mD

A: 2 x 3
B: 2 x 2
C: 3 x 2
D: 2 x 3
u: 1 x 4
w: 4 x 1
[[9, 7, -4, 9]]
[[3, -3, -2, 1]]
[[36, 12, -18, 30]]
[[18, 10, 3, 20]]
8.60232526704
[[-4, -7, -3], [3, 6, 4]]
[[14, 3, 3], [2, 7, 9]]
[[-1 -5 -1]
 [ 2  7  4]]
[[ 5 -6]
 [ 9 -8]
 [ 6 -6]]
[[ 1 -4]
 [ 0  1]]
[[14 28]
 [28 69]]
[[10 -4  0]
 [-4  8  8]
 [ 0  8 10]]


In [384]:
import thinkplot

ImportError: No module named thinkplot